import json

import pytest

from firmware.normalizer import normalize_component, normalize_model, normalize_platform
from recipe.loader import RecipeLoadError, load_recipe
from recipe.validator import validate_recipe

HEADER = "Platform,Model,Category,Component,Target Version,Target Build,Mandatory\n"
GOOD_ROWS = (
    "Superdome Flex,SD Flex 280,Server,RMC,3.10.5,,Yes\n"
    "HPE DL,DL380 Gen11,Server,BIOS,U54 v2.12,,Yes\n"
    "VMware,ESXi,ESXi,ESXi,8.0.3,24022510,Yes\n"
)


def write(tmp_path, name, text):
    path = tmp_path / name
    path.write_text(text, encoding="utf-8")
    return path


# ------------------------------------------------------------------ normalization


@pytest.mark.parametrize(
    "value", ["iLO", "ILO", "iLO Firmware", "Integrated Lights-Out", "ILO VERSION"]
)
def test_ilo_normalizes(value):
    assert normalize_component(value) == "ilo"


@pytest.mark.parametrize(
    "value,expected",
    [
        ("BIOS", "bios"),
        ("System ROM", "bios"),
        ("SPS Firmware", "sps"),
        ("Server Platform Services", "sps"),
        ("Intelligent Provisioning", "intelligent_provisioning"),
        ("RMC", "rmc"),
        ("Resource Management Controller", "rmc"),
        ("Switch Firmware", "switch_firmware"),
        ("OS Version", "os_version"),
        ("ESXi", "esxi"),
    ],
)
def test_component_normalization(value, expected):
    assert normalize_component(value, recipe_context=True) == expected


def test_ip_means_intelligent_provisioning_only_in_a_recipe():
    assert normalize_component("IP", recipe_context=True) == "intelligent_provisioning"
    assert normalize_component("IP") != "intelligent_provisioning"


@pytest.mark.parametrize(
    "value,expected",
    [
        ("SD Flex 280", "superdome_flex_280"),
        ("Superdome Flex 280", "superdome_flex_280"),
        ("Superdome Flex", "superdome_flex"),
        ("CSUS 3200", "csus_3200"),
        ("Compute Scale-up Server 3200", "csus_3200"),
        ("HPE ProLiant DL380 Gen11", "hpe_dl"),
        ("Aruba CX 8325 Switch", "switch"),
        ("VMware ESXi", "vmware_esxi"),
    ],
)
def test_platform_normalization(value, expected):
    assert normalize_platform(value) == expected


def test_model_normalization_drops_vendor_noise():
    assert normalize_model("HPE ProLiant DL380 Gen 11") == "dl380_gen11"
    assert normalize_model("*") == ""
    assert normalize_model("") == ""


# ------------------------------------------------------------------- loading


def test_load_csv(tmp_path):
    raw = load_recipe(write(tmp_path, "r.csv", HEADER + GOOD_ROWS))
    assert len(raw.rows) == 3
    assert not raw.missing_required


def test_load_csv_with_preamble_rows(tmp_path):
    text = "Firmware recipe 2026\nGenerated by the platform team\n\n" + HEADER + GOOD_ROWS
    raw = load_recipe(write(tmp_path, "r.csv", text))
    assert len(raw.rows) == 3


def test_load_json(tmp_path):
    payload = [
        {
            "Platform": "HPE DL",
            "Model": "DL380 Gen11",
            "Category": "Server",
            "Component": "iLO",
            "Target Version": "6.10",
        }
    ]
    raw = load_recipe(write(tmp_path, "r.json", json.dumps(payload)))
    assert len(raw.rows) == 1
    assert raw.rows[0]["component"] == "iLO"


def test_load_rejects_unknown_extension(tmp_path):
    with pytest.raises(RecipeLoadError):
        load_recipe(write(tmp_path, "r.txt", HEADER))


def test_load_rejects_missing_header(tmp_path):
    with pytest.raises(RecipeLoadError):
        load_recipe(write(tmp_path, "r.csv", "a,b,c\n1,2,3\n"))


def test_missing_header_error_shows_what_was_found(tmp_path):
    """The error has to be diagnosable without opening the file."""
    text = "Server Name,Serial,Location\nsrv001,CZ123,Bangalore\n"
    with pytest.raises(RecipeLoadError) as excinfo:
        load_recipe(write(tmp_path, "r.csv", text))
    message = str(excinfo.value)
    assert "Server Name" in message
    assert "Platform" in message


def test_alternative_column_spellings_are_accepted(tmp_path):
    text = (
        "HW Platform,Server Model,Device Type,FW Component,Recommended Version\n"
        "HPE DL,DL380 Gen11,Server,BIOS,U54 v2.12\n"
    )
    raw = load_recipe(write(tmp_path, "r.csv", text))
    assert not raw.missing_required
    report = validate_recipe(raw)
    assert report.ok
    assert report.entries[0].component_key == "bios"
    assert report.entries[0].target_version == "U54 v2.12"


def test_semicolon_delimited_csv(tmp_path):
    text = HEADER.replace(",", ";") + GOOD_ROWS.replace(",", ";")
    raw = load_recipe(write(tmp_path, "r.csv", text))
    assert len(raw.rows) == 3


def test_legacy_xls_is_rejected_with_advice(tmp_path):
    with pytest.raises(RecipeLoadError) as excinfo:
        load_recipe(write(tmp_path, "r.xls", HEADER))
    assert "xlsx" in str(excinfo.value)


# ---------------------------------------------------------------- validation


def test_valid_recipe(tmp_path):
    report = validate_recipe(load_recipe(write(tmp_path, "r.csv", HEADER + GOOD_ROWS)))
    assert report.ok
    assert len(report.entries) == 3
    entry = report.entries[0]
    assert entry.platform_key == "superdome_flex_280"
    assert entry.component_key == "rmc"
    assert entry.target_version == "3.10.5"
    assert entry.mandatory is True


def test_missing_column(tmp_path):
    text = "Platform,Model,Component,Target Version\nHPE DL,DL380 Gen11,BIOS,U54 v2.12\n"
    report = validate_recipe(load_recipe(write(tmp_path, "r.csv", text)))
    assert not report.ok
    assert any("Category" in issue.message for issue in report.errors)


def test_missing_component_is_reported_with_row_number(tmp_path):
    text = HEADER + "HPE DL,DL380 Gen11,Server,,U54 v2.12,,Yes\n"
    report = validate_recipe(load_recipe(write(tmp_path, "r.csv", text)))
    assert not report.ok
    assert any(issue.row == 2 and "Component" in issue.message for issue in report.errors)


def test_missing_target_version(tmp_path):
    text = HEADER + "HPE DL,DL380 Gen11,Server,BIOS,,,Yes\n"
    report = validate_recipe(load_recipe(write(tmp_path, "r.csv", text)))
    assert any("Target Version is missing" in issue.message for issue in report.errors)


def test_duplicate_entries(tmp_path):
    text = HEADER + (
        "HPE DL,DL380 Gen11,Server,BIOS,U54 v2.12,,Yes\n"
        "HPE DL,DL380 Gen11,Server,BIOS,U54 v2.10,,Yes\n"
    )
    report = validate_recipe(load_recipe(write(tmp_path, "r.csv", text)))
    assert not report.ok
    assert any("Duplicate entry" in issue.message for issue in report.errors)


def test_invalid_version_value(tmp_path):
    text = HEADER + "HPE DL,DL380 Gen11,Server,BIOS,latest,,Yes\n"
    report = validate_recipe(load_recipe(write(tmp_path, "r.csv", text)))
    assert any("not a recognisable version" in issue.message for issue in report.errors)


def test_unsupported_component(tmp_path):
    text = HEADER + "HPE DL,DL380 Gen11,Server,Flux Capacitor,1.0,,Yes\n"
    report = validate_recipe(load_recipe(write(tmp_path, "r.csv", text)))
    assert any("not a supported component" in issue.message for issue in report.errors)


def test_unsupported_category(tmp_path):
    text = HEADER + "HPE DL,DL380 Gen11,Toaster,BIOS,U54 v2.12,,Yes\n"
    report = validate_recipe(load_recipe(write(tmp_path, "r.csv", text)))
    assert any("not a supported category" in issue.message for issue in report.errors)


def test_empty_recipe(tmp_path):
    report = validate_recipe(load_recipe(write(tmp_path, "r.csv", HEADER)))
    assert not report.ok
    assert any("no data rows" in issue.message for issue in report.errors)


def test_blank_rows_are_skipped_not_rejected(tmp_path):
    text = HEADER + GOOD_ROWS + ",,,,,,\n\n"
    report = validate_recipe(load_recipe(write(tmp_path, "r.csv", text)))
    assert report.ok
    assert report.skipped_empty >= 1


def test_not_applicable_target(tmp_path):
    text = HEADER + "HPE DL,DL360 Gen11,Server,SPS,N/A,,No\n"
    report = validate_recipe(load_recipe(write(tmp_path, "r.csv", text)))
    assert report.ok
    assert report.entries[0].not_applicable is True
    assert report.entries[0].mandatory is False


def test_wildcard_model_becomes_family_rule(tmp_path):
    text = HEADER + "Aruba,*,Switch,Switch Firmware,10.5.1,,Yes\n"
    report = validate_recipe(load_recipe(write(tmp_path, "r.csv", text)))
    assert report.ok
    assert report.entries[0].applies_to_family is True
    assert report.entries[0].model_key == ""


def test_build_must_be_numeric(tmp_path):
    text = HEADER + "VMware,ESXi,ESXi,ESXi,8.0.3,abc,Yes\n"
    report = validate_recipe(load_recipe(write(tmp_path, "r.csv", text)))
    assert any("must be numeric" in issue.message for issue in report.errors)
